// Builds Toucan's glyphs from their designs in
// src/features/glyphs/glyphDesign.consts.ts: bakes each into a plain filled
// path (src/generated/glyphPaths.ts, which the swatches and the sidebar block
// draw), writes the SVG sources, and builds the icon font
// media/toucan-icons.woff from them, so the font and the swatches can't drift
// apart.
//
// The SVGs go to packages/brand/assets/glyphs/, the one place this repo writes
// into another package (ADR-0014): the brand holds the glyph shapes the site
// shows, while the designs, the bake and the font stay with the extension,
// which VS Code loads the font from.
// import libraries
import { mkdirSync, writeFileSync } from "node:fs";

// import utils
import { FONT_CODEPOINTS, shapeSvg } from "../src/features/glyphs/glyphFont.util.ts";
import { asHex } from "../src/shared/color/hex.util.ts";
import { bakeGlyph } from "./bake-glyphs.mts";
import { buildFont } from "./font.mts";

// import consts
import { GLYPHS } from "@toucan/brand/glyphs.consts.ts";
import { GLYPH_DESIGNS } from "../src/features/glyphs/glyphDesign.consts.ts";

const ROOT = new URL("../", import.meta.url);
const MEDIA = new URL("media/", ROOT);
const ICONS = new URL("../../packages/brand/assets/glyphs/", ROOT);
const BLACK = asHex("#000000");

const paths = GLYPHS.map((glyph) => {
  const { width } = GLYPH_DESIGNS[glyph];
  return { glyph, width, d: bakeGlyph(GLYPH_DESIGNS[glyph]) };
});

writeFileSync(
  new URL("src/generated/glyphPaths.ts", ROOT),
  [
    "// Generated by `pnpm font` from src/features/glyphs/glyphDesign.consts.ts. Do not edit.",
    'import type { Glyph } from "@toucan/brand/glyphs.types.ts";',
    "",
    "/** Each glyph as one plain filled path (nonzero), 16 units high. */",
    "export const GLYPH_PATHS: Record<Glyph, { width: number; d: string }> = {",
    ...paths.map(
      ({ glyph, width, d }) =>
        `  ${JSON.stringify(glyph)}: { width: ${width}, d: ${JSON.stringify(d)} },`,
    ),
    "};",
    "",
  ].join("\n"),
);

mkdirSync(ICONS, { recursive: true });

// From the freshly baked paths, not the module this script imported, which
// still holds the previous run's output.
const icons = paths.map(({ glyph, width, d }) => {
  const svg = shapeSvg({ width, d, color: BLACK });
  writeFileSync(new URL(`${glyph}.svg`, ICONS), `${svg}\n`);
  return { name: glyph, codepoint: FONT_CODEPOINTS[glyph], svg };
});
const { woff } = await buildFont(icons);
writeFileSync(new URL("toucan-icons.woff", MEDIA), woff);
console.log(
  "Wrote src/generated/glyphPaths.ts, media/toucan-icons.woff and packages/brand/assets/glyphs/*.svg",
);
