// Builds Toucan's glyphs from their designs in src/core/glyphDesign.ts: bakes
// each into a plain filled path (src/generated/glyphPaths.ts, which the
// swatches and the sidebar block draw), writes the SVG sources to
// media/icons, and builds the icon font media/toucan-icons.woff from them, so
// the font and the swatches can't drift apart.
import { mkdirSync, writeFileSync } from "node:fs";
import { GLYPH_DESIGNS } from "../src/features/glyphs/glyphDesign.consts.ts";
import { FONT_CODEPOINTS, shapeSvg } from "../src/features/glyphs/glyphFont.util.ts";
import { GLYPHS } from "../src/shared/model/model.consts.ts";
import { asHex } from "../src/shared/color/hex.util.ts";
import { bakeGlyph } from "./bake-glyphs.mts";
import { buildFont } from "./font.mts";

const ROOT = new URL("../", import.meta.url);
const MEDIA = new URL("media/", ROOT);
const ICONS = new URL("icons/", MEDIA);
const BLACK = asHex("#000000");

const paths = GLYPHS.map((glyph) => {
  const { width } = GLYPH_DESIGNS[glyph];
  return { glyph, width, d: bakeGlyph(GLYPH_DESIGNS[glyph]) };
});

writeFileSync(
  new URL("src/generated/glyphPaths.ts", ROOT),
  [
    "// Generated by `pnpm font` from src/features/glyphs/glyphDesign.consts.ts. Do not edit.",
    'import type { Glyph } from "../shared/model/model.types.ts";',
    "",
    "/** Each glyph as one plain filled path (nonzero), 16 units high. */",
    "export const GLYPH_PATHS: Record<Glyph, { width: number; d: string }> = {",
    ...paths.map(
      ({ glyph, width, d }) =>
        `  ${JSON.stringify(glyph)}: { width: ${width}, d: ${JSON.stringify(d)} },`,
    ),
    "};",
    "",
  ].join("\n"),
);

mkdirSync(ICONS, { recursive: true });

// From the freshly baked paths, not the module this script imported, which
// still holds the previous run's output.
const icons = paths.map(({ glyph, width, d }) => {
  const svg = shapeSvg(width, d, BLACK);
  writeFileSync(new URL(`${glyph}.svg`, ICONS), `${svg}\n`);
  return { name: glyph, codepoint: FONT_CODEPOINTS[glyph], svg };
});
const { woff } = await buildFont(icons);
writeFileSync(new URL("toucan-icons.woff", MEDIA), woff);
console.log("Wrote src/generated/glyphPaths.ts, media/icons/*.svg and media/toucan-icons.woff");
